language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0

env:
  - NETTE=nette-2.4
  - NETTE=nette-2.3

matrix:
  include:
    - php: 7.0
      env: COVERAGE="--coverage-clover=./coverage.xml"

before_install:
  - wget https://raw.githubusercontent.com/Kdyby/TesterExtras/master/bin/composer-nette.php
  - php ./composer-nette.php

install:
  - composer install --no-interaction --prefer-dist

script:
  - ./vendor/bin/phpunit $COVERAGE

after_success:
  - >
    if [ "$COVERAGE" != "" ]; then
    wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
    && php ./coveralls.phar --verbose
    || true; fi
